# GNU Affero General Public License v3.0 or later (see COPYING or https://www.gnu.org/licenses/agpl.txt)

FROM ghcr.io/t-c-l-o-u-d/config-devcontainer/arch-linux-devcontainer-base:latest

# pull in USER from devcontainer.json
ARG USER

# add the USER to the image
RUN useradd --create-home --groups wheel ${USER}

# =======================================
# repository specific commands start here
# =======================================

# add bash files
#COPY playground-rust-devcontainer /etc/skel/.config/bash/playground-rust-devcontainer
COPY playground-rust-devcontainer /etc/skel/.config/bash/

# install rust toolchain
RUN pacman --sync --noconfirm \
    llvm-libs \
    rust \
    rust-analyzer \
    rust-src \
    sccache

# =====================================
# repository specific commands end here
# =====================================

# ensure the image starts as USER
USER ${USER}
